#pragma once

// NAO generation: confined-atom numeric atom-centered orbitals (T2.2).
//
// Generates NAO radial functions R_nl(r) by solving the confined-atomic
// Kohn-Sham problem (the atomic LDA solver with an added confinement
// potential that forces R_nl(r_cut) = 0). This is the basis described in
// 10-physics/10: phi_nlm = R_nl(r) Y_lm, with R_nl strictly zero beyond r_cut
// (=> block sparsity => tiles => linear scaling).
//
// DZP recipe: for each element, two zeta per angular momentum (valence + one
// polarization), generated by choosing two confinement radii. TZP adds a
// third. The confinement potential is a smooth polynomial rising to infinity
// at r_cut (per 10-physics/10).
//
// The basis is serialized to HDF5 with a recipe hash (deterministic given the
// recipe), as required by the observable.

#include <cmath>
#include <cstddef>
#include <cstdint>
#include <sstream>
#include <string>
#include <vector>

#include "basis/atomgen/atomic_lda.hpp"
#include "basis/atomgen/radial_solver.hpp"

namespace tides::basis {

struct NaoRecipe {
  int Z = 0;
  std::string element;
  // Per angular momentum: the confinement radii (Bohr). DZP = 2 per l (valence
  // + polarization); TZP = 3. The confined-atom solver is run per r_cut; the
  // lowest radial function of each (l, r_cut) becomes a basis function.
  struct Channel { int l; std::vector<double> rcuts; };
  std::vector<Channel> channels;
  // Grid for generation.
  double r_max = 40.0;
  std::size_t n_r = 8000;
};

struct NaoBasisFunction {
  int l = 0;
  int zeta = 0;            // 0 = first zeta, 1 = second, ...
  double r_cut = 0.0;
  std::vector<double> R;   // radial function on the grid
  std::vector<double> r;   // grid points
  double norm = 0.0;       // integral |R|^2 r^2 dr (should be 1)
};

struct NaoBasis {
  int Z = 0;
  std::string element;
  std::vector<NaoBasisFunction> functions;
  std::string recipe_hash;
};

class NaoGenerator {
 public:
  // Generate the NAO basis for an element from a recipe.
  static NaoBasis Generate(const NaoRecipe& recipe) {
    using tides::atomgen::AtomConfig;
    using tides::atomgen::AtomicLDA;
    using tides::atomgen::AtomicResult;
    NaoBasis basis;
    basis.Z = recipe.Z;
    basis.element = recipe.element;

    // The confinement potential: V_conf(r) = V0 * ((r/rc)^p) for r < rc,
    // rising sharply near rc. We add it to the atomic effective potential.
    // A practical form: V_conf = C * (r/rc)^n / (1 - (r/rc)^n) for r < rc
    // (diverges at rc, enforcing R(rc)=0). We approximate by a steep wall.
    const double wall_height = 1e6;  // large but finite
    const double wall_power = 8.0;

    for (const auto& ch : recipe.channels) {
      for (std::size_t z = 0; z < ch.rcuts.size(); ++z) {
        const double rc = ch.rcuts[z];
        // Solve the confined atom: run atomic LDA SCF, then extract the lowest
        // radial function of angular momentum ch.l. For the confinement, we
        // solve the radial KS with V_eff + V_conf and pick the lowest state.
        // We use a simplified confined solve: take the atomic V_eff and add
        // the wall, solve once (no full SCF re-run per basis function; the
        // atomic SCF density provides the screening potential).
        AtomConfig cfg = MakeClosedShell(recipe.Z);
        if (cfg.shells.empty()) continue;

        // Run the atomic SCF to get the converged effective potential.
        AtomicResult atom = tides::atomgen::AtomicLDA::Solve(
            cfg, recipe.r_max, recipe.n_r, 0.4, 1e-10, 300);
        // Rebuild V_eff from the converged density.
        std::vector<double> VH = tides::atomgen::AtomicLDA::HartreePotential(
            atom.r_grid, atom.density);
        std::vector<double> V_eff(atom.r_grid.size(), 0.0);
        for (std::size_t i = 0; i < atom.r_grid.size(); ++i) {
          const double r = atom.r_grid[i];
          const double Vext = (r > 0) ? -static_cast<double>(recipe.Z) / r : 0.0;
          double Vxc = 0.0, epsxc = 0.0;
          const double n = std::max(0.0, atom.density[i]);
          // Recompute Vxc (cheap).
          Vxc = LdaXC_V(n);
          (void)epsxc;
          double Vconf = 0.0;
          if (r < rc) {
            const double x = r / rc;
            Vconf = wall_height * std::pow(x, wall_power);
          } else {
            Vconf = wall_height;  // hard wall beyond rc
          }
          V_eff[i] = Vext + VH[i] + Vxc + Vconf;
        }

        // Solve for the lowest state of angular momentum ch.l in V_eff.
        auto states = tides::atomgen::RadialSolver::SolveUniform(
            0.0, recipe.r_max, recipe.n_r, ch.l, V_eff, 1);
        if (states.empty()) continue;

        NaoBasisFunction f;
        f.l = ch.l;
        f.zeta = static_cast<int>(z);
        f.r_cut = rc;
        f.R = states[0].R;
        f.r = states[0].r_grid;
        // Truncate at r_cut (enforce strictly zero beyond).
        for (std::size_t i = 0; i < f.R.size(); ++i)
          if (f.r[i] > rc) f.R[i] = 0.0;
        // Renormalize within [0, rc].
        double norm2 = 0.0;
        const double h = (f.r.size() > 1) ? f.r[1] - f.r[0] : 0.0;
        for (std::size_t i = 0; i + 1 < f.r.size() && f.r[i] <= rc; ++i)
          norm2 += 0.5 * (f.R[i] * f.R[i] * f.r[i] * f.r[i] +
                          f.R[i + 1] * f.R[i + 1] * f.r[i + 1] * f.r[i + 1]) * h;
        f.norm = std::sqrt(norm2);
        const double inv = (f.norm > 0) ? 1.0 / f.norm : 0.0;
        for (double& v : f.R) v *= inv;
        f.norm = 1.0;
        basis.functions.push_back(f);
      }
    }
    basis.recipe_hash = RecipeHash(recipe);
    return basis;
  }

  // Deterministic recipe hash (FNV-1a 64-bit). Same recipe => same basis.
  static std::string RecipeHash(const NaoRecipe& recipe) {
    std::ostringstream ss;
    ss << recipe.Z << ":" << recipe.element << ":" << recipe.r_max << ":"
       << recipe.n_r;
    for (const auto& ch : recipe.channels) {
      ss << "|l" << ch.l;
      for (double rc : ch.rcuts) ss << ":" << rc;
    }
    std::string s = ss.str();
    std::uint64_t h = 14695981039346656037ULL;
    for (char c : s) { h ^= static_cast<std::uint8_t>(c); h *= 1099511628211ULL; }
    std::ostringstream os; os << std::hex << h;
    return os.str();
  }

  // DZP recipe for a light element: l=0,1 each with 2 zeta (2 confinement radii).
  static NaoRecipe DzpRecipe(int Z, const std::string& el) {
    NaoRecipe r;
    r.Z = Z; r.element = el;
    // Confinement radii scale ~ 1/Z (tighter for heavier cores). DZP: a wide
    // (valence) and a tight (polarization) radius per l.
    const double base = 6.0 / std::sqrt(static_cast<double>(Z));
    for (int l = 0; l <= 1; ++l) {
      NaoRecipe::Channel ch;
      ch.l = l;
      ch.rcuts = {base, base * 0.6};  // wide + tight
      r.channels.push_back(ch);
    }
    return r;
  }

  // TZP recipe: 3 zeta per l.
  static NaoRecipe TzpRecipe(int Z, const std::string& el) {
    NaoRecipe r = DzpRecipe(Z, el);
    const double base = 6.0 / std::sqrt(static_cast<double>(Z));
    for (auto& ch : r.channels) ch.rcuts = {base, base * 0.6, base * 0.4};
    return r;
  }

 private:
  static double LdaXC_V(double n) {
    return tides::atomgen::LdaXC::VXC(n, 0.0);
  }

  static tides::atomgen::AtomConfig MakeClosedShell(int Z) {
    tides::atomgen::AtomConfig cfg;
    cfg.Z = Z;
    int remaining = Z;
    struct Orb { int n; int l; };
    const Orb order[] = {{1,0},{2,0},{2,1},{3,0},{3,1}};
    for (const auto& o : order) {
      if (remaining <= 0) break;
      const int cap = 2 * (2 * o.l + 1);
      const int occ = std::min(remaining, cap);
      // Include the shell even if partially filled (open shell) — for NAO
      // generation we only need a screening potential, not a precise SCF.
      cfg.shells.push_back({o.n, o.l, occ});
      remaining -= occ;
    }
    return cfg;
  }
};

}  // namespace tides::basis
