# CMake generated Testfile for 
# Source directory: /home/niel/git/New_DFT_Code/tides
# Build directory: /home/niel/git/New_DFT_Code/build-cuda
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[tilemat_analytical_invariants]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_tilemat_tests")
set_tests_properties([=[tilemat_analytical_invariants]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;22;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[tilemat_hdf5_stage_dump_schema]=] "/usr/bin/python3" "/home/niel/git/New_DFT_Code/tides/core/tile/tests/tilemat_hdf5_roundtrip_test.py" "--fixture" "/home/niel/git/New_DFT_Code/build-cuda/tides_tilemat_dump_fixture" "--bridge" "/home/niel/git/New_DFT_Code/tides/tools/tilemat_hdf5.py" "--work-dir" "/home/niel/git/New_DFT_Code/build-cuda/tilemat_hdf5_roundtrip")
set_tests_properties([=[tilemat_hdf5_stage_dump_schema]=] PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;30;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[spgemm_filtered_analytical_bounds]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_spgemm_filtered_tests")
set_tests_properties([=[spgemm_filtered_analytical_bounds]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;45;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[precision_descriptor_and_ledger_contracts]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_precision_tests")
set_tests_properties([=[precision_descriptor_and_ledger_contracts]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;52;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[tile_ops_analytical_contracts]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_ops_tests")
set_tests_properties([=[tile_ops_analytical_contracts]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;56;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[f64e_reference_adversarial_numerics]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_f64e_reference_tests")
set_tests_properties([=[f64e_reference_adversarial_numerics]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;63;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[ozaki_fp16_slice_planning_contracts]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_ozaki_slice_tests")
set_tests_properties([=[ozaki_fp16_slice_planning_contracts]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;70;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp1_deterministic_substrate_gauntlet]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_deterministic_gauntlet_tests")
set_tests_properties([=[wp1_deterministic_substrate_gauntlet]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;79;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[cuda_grouped_gemm_fp64_oracle]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_cuda_gemm_tests")
set_tests_properties([=[cuda_grouped_gemm_fp64_oracle]=] PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;109;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[cuda_graph_replay_fp64_oracle]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_cuda_graph_tests")
set_tests_properties([=[cuda_graph_replay_fp64_oracle]=] PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;123;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[cuda_deterministic_substrate_gauntlet]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_cuda_determinism_tests")
set_tests_properties([=[cuda_deterministic_substrate_gauntlet]=] PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;137;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[cuda_f64e_reduction_analytical_contracts]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_cuda_reduce_f64e_tests")
set_tests_properties([=[cuda_f64e_reduction_analytical_contracts]=] PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;161;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[cuda_filtered_spgemm_fp64_oracle]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_cuda_spgemm_tests")
set_tests_properties([=[cuda_filtered_spgemm_fp64_oracle]=] PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;177;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[cuda_ozaki_f64e_gemm_vs_fp64_oracle]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_cuda_ozaki_gemm_tests")
set_tests_properties([=[cuda_ozaki_f64e_gemm_vs_fp64_oracle]=] PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;192;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[cuda_two_center_tile_assembly]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_cuda_two_center_tests")
set_tests_properties([=[cuda_two_center_tile_assembly]=] PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;212;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[cuda_rho_build_vs_cpu]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_cuda_rho_build_tests")
set_tests_properties([=[cuda_rho_build_vs_cpu]=] PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;234;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[cuda_poisson_fft_vs_cpu]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_cuda_poisson_fft_tests")
set_tests_properties([=[cuda_poisson_fft_vs_cpu]=] PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;246;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[cuda_xc_lda_vs_cpu]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_cuda_xc_tests")
set_tests_properties([=[cuda_xc_lda_vs_cpu]=] PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;258;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp2_atomgen_eigensolver_analytical]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_atomgen_eigensolver_tests")
set_tests_properties([=[wp2_atomgen_eigensolver_analytical]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;290;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp2_atomgen_hydrogenic_eigenvalues]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_atomgen_hydrogenic_tests")
set_tests_properties([=[wp2_atomgen_hydrogenic_eigenvalues]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;296;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp2_lda_xc_vs_libxc]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_lda_xc_tests")
set_tests_properties([=[wp2_lda_xc_vs_libxc]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;307;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp2_atomic_lda_ne_total_energy]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_atomic_lda_tests")
set_tests_properties([=[wp2_atomic_lda_ne_total_energy]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;312;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp2_pseudo_validators_and_ghost_detector]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_pseudo_tests")
set_tests_properties([=[wp2_pseudo_validators_and_ghost_detector]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;317;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp2_two_center_rotation_invariance_and_spline]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_two_center_tests")
set_tests_properties([=[wp2_two_center_rotation_invariance_and_spline]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;323;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp2_derivative_streams_fd_validation]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_derivative_tests")
set_tests_properties([=[wp2_derivative_streams_fd_validation]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;329;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp2_pyscf_overlap_cross_check]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_pyscf_overlap_tests")
set_tests_properties([=[wp2_pyscf_overlap_cross_check]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;335;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp2_nao_generation]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_nao_tests")
set_tests_properties([=[wp2_nao_generation]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;340;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp3_dual_grid_index_map_and_halo]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_dual_grid_tests")
set_tests_properties([=[wp3_dual_grid_index_map_and_halo]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;364;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp3_poisson_gaussian_charge_all_bcs]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_poisson_tests")
set_tests_properties([=[wp3_poisson_gaussian_charge_all_bcs]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;370;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp3_rho_adjoint_xc_grid_ops]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_grid_ops_tests")
set_tests_properties([=[wp3_rho_adjoint_xc_grid_ops]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;376;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp4_solvers_broker_chfsi_omm]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_wp4_tests")
set_tests_properties([=[wp4_solvers_broker_chfsi_omm]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;392;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp5_sp2_submatrix_foe_fermi_truncation]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_wp5_tests")
set_tests_properties([=[wp5_sp2_submatrix_foe_fermi_truncation]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;397;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp6_scf_forces_xlbomd_optimizers_stress]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_wp6_tests")
set_tests_properties([=[wp6_scf_forces_xlbomd_optimizers_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;412;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp7_hybrids_d3_isdf_ace_paw]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_wp7_tests")
set_tests_properties([=[wp7_hybrids_d3_isdf_ace_paw]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;427;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp8_stage_dump_partitioner_halo_packaging]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_wp8_tests")
set_tests_properties([=[wp8_stage_dump_partitioner_halo_packaging]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;438;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
add_test([=[wp9_ladder_runner_reference_data_ab_fd_dashboard]=] "/home/niel/git/New_DFT_Code/build-cuda/tides_wp9_tests")
set_tests_properties([=[wp9_ladder_runner_reference_data_ab_fd_dashboard]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;449;add_test;/home/niel/git/New_DFT_Code/tides/CMakeLists.txt;0;")
